name: nourish_mart
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.2.6 <4.0.0'

# cloud_firestore, cupertino_icons, dio, envied, firebase_analytics, firebase_core,
# firebase_crashlytics, flutter_svg, fluttertoast, focus_detector, get, get_storage,
# internet_connection_checker_plus, intl, lottie, pinput
dependencies:
  cloud_firestore: ^4.15.4
  cupertino_icons: ^1.0.6
  dio: ^5.4.0
  envied: ^0.5.3
  firebase_analytics: ^10.8.5
  firebase_auth: ^4.10.0
  firebase_core: ^2.25.4
  firebase_crashlytics: ^3.4.14
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  fluttertoast: ^8.2.4
  focus_detector: ^2.0.1
  get: ^4.6.6
  get_storage: ^2.1.1
  internet_connection_checker_plus: ^2.2.0
  intl: ^0.19.0
  lottie: ^3.0.0
  pinput: ^4.0.0

# build_runner, envied_generator, flutter_lints
dev_dependencies:
  build_runner: ^2.4.8
  envied_generator: ^0.5.3
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/gifs/
    - pubspec.yaml

  fonts:
    - family: inter
      fonts:
        - asset: assets/fonts/inter_regular.ttf
          style: normal
