// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB97ZugT-vSh3n3qdDgbjiPr3Vc6qLIpX4',
    appId: '1:303973469851:web:ec1b0c09f098bb4c19003e',
    messagingSenderId: '303973469851',
    projectId: 'nurishmart-auth',
    authDomain: 'nurishmart-auth.firebaseapp.com',
    storageBucket: 'nurishmart-auth.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe4KdTfELVku5Qtn5LFRPlZY0BoJ1zDZg',
    appId: '1:303973469851:android:0dce98bbb7ff6caa19003e',
    messagingSenderId: '303973469851',
    projectId: 'nurishmart-auth',
    storageBucket: 'nurishmart-auth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1JlRRNsUJIeSigqYQq-yBLv-7Bnxf00g',
    appId: '1:303973469851:ios:ddc78ab31d8ad0da19003e',
    messagingSenderId: '303973469851',
    projectId: 'nurishmart-auth',
    storageBucket: 'nurishmart-auth.appspot.com',
    iosBundleId: 'com.example.nourishMart',
  );
}
